# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoPassboltCli < Formula
  desc "A CLI tool to interact with Passbolt, a Open source Password Manager for Teams"
  homepage "https://github.com/passbolt/go-passbolt-cli"
  version "0.2.1-rc"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/passbolt/go-passbolt-cli/releases/download/v0.2.1-rc/go-passbolt-cli_0.2.1-rc_darwin_arm64.tar.gz"
      sha256 "252c3ba8ee56fbd4b575f868c6da40baaf8a7d706a5f065180d45046a37bac72"

      def install
        bin.install "passbolt"
        bash_completion.install "/home/runner/work/go-passbolt-cli/go-passbolt-cli/completion/bash" => "passbolt"
        zsh_completion.install "/home/runner/work/go-passbolt-cli/go-passbolt-cli/completion/zsh" => "_passbolt"
        fish_completion.install "/home/runner/work/go-passbolt-cli/go-passbolt-cli/completion/fish" => "passbolt.fish"
        man1.install "/home/runner/work/go-passbolt-cli/go-passbolt-cli/man/*"
        # ...
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/passbolt/go-passbolt-cli/releases/download/v0.2.1-rc/go-passbolt-cli_0.2.1-rc_darwin_amd64.tar.gz"
      sha256 "fb9b75cfc35c12dfd3e7e259930bc510c5d9a7bb3a98656e49b16cf1357e45cb"

      def install
        bin.install "passbolt"
        bash_completion.install "/home/runner/work/go-passbolt-cli/go-passbolt-cli/completion/bash" => "passbolt"
        zsh_completion.install "/home/runner/work/go-passbolt-cli/go-passbolt-cli/completion/zsh" => "_passbolt"
        fish_completion.install "/home/runner/work/go-passbolt-cli/go-passbolt-cli/completion/fish" => "passbolt.fish"
        man1.install "/home/runner/work/go-passbolt-cli/go-passbolt-cli/man/*"
        # ...
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/passbolt/go-passbolt-cli/releases/download/v0.2.1-rc/go-passbolt-cli_0.2.1-rc_linux_arm64.tar.gz"
      sha256 "bdf738beb13916caa002378471e69444cd090ef557d29793a7d1e29c6e3f427a"

      def install
        bin.install "passbolt"
        bash_completion.install "/home/runner/work/go-passbolt-cli/go-passbolt-cli/completion/bash" => "passbolt"
        zsh_completion.install "/home/runner/work/go-passbolt-cli/go-passbolt-cli/completion/zsh" => "_passbolt"
        fish_completion.install "/home/runner/work/go-passbolt-cli/go-passbolt-cli/completion/fish" => "passbolt.fish"
        man1.install "/home/runner/work/go-passbolt-cli/go-passbolt-cli/man/*"
        # ...
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/passbolt/go-passbolt-cli/releases/download/v0.2.1-rc/go-passbolt-cli_0.2.1-rc_linux_amd64.tar.gz"
      sha256 "9ebdfae4273fddd3b6ff8e016ed87464578f785de6df41a5fbf12f1fdb77df8b"

      def install
        bin.install "passbolt"
        bash_completion.install "/home/runner/work/go-passbolt-cli/go-passbolt-cli/completion/bash" => "passbolt"
        zsh_completion.install "/home/runner/work/go-passbolt-cli/go-passbolt-cli/completion/zsh" => "_passbolt"
        fish_completion.install "/home/runner/work/go-passbolt-cli/go-passbolt-cli/completion/fish" => "passbolt.fish"
        man1.install "/home/runner/work/go-passbolt-cli/go-passbolt-cli/man/*"
        # ...
      end
    end
  end
end
