# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoPassboltCli < Formula
  desc "A CLI tool to interact with Passbolt, a Open source Password Manager for Teams"
  homepage "https://github.com/passbolt/go-passbolt-cli"
  version "0.4.0-beta.1"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/passbolt/go-passbolt-cli/releases/download/v0.4.0-beta.1/go-passbolt-cli_0.4.0-beta.1_darwin_amd64.tar.gz"
      sha256 "350a013de8186d65b7eb804c26e56bc8bd9be7e93b2e5f5756af960fac5ff696"

      def install
        bin.install "passbolt"
        bash_completion.install "completion/bash" => "passbolt"
        zsh_completion.install "completion/zsh" => "_passbolt"
        fish_completion.install "completion/fish" => "passbolt.fish"
        man1.install Dir["man/*"]
        # ...
      end
    end
    on_arm do
      url "https://github.com/passbolt/go-passbolt-cli/releases/download/v0.4.0-beta.1/go-passbolt-cli_0.4.0-beta.1_darwin_arm64.tar.gz"
      sha256 "a2dc07055029380e40a51f2e296245662f01b7da8a4b7dd66afbbeb3c9bdb6de"

      def install
        bin.install "passbolt"
        bash_completion.install "completion/bash" => "passbolt"
        zsh_completion.install "completion/zsh" => "_passbolt"
        fish_completion.install "completion/fish" => "passbolt.fish"
        man1.install Dir["man/*"]
        # ...
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/passbolt/go-passbolt-cli/releases/download/v0.4.0-beta.1/go-passbolt-cli_0.4.0-beta.1_linux_amd64.tar.gz"
        sha256 "3b4541471a5d87242a00ab6fe381be3c75b077fc7c29f3bf69e0becfadc3254c"

        def install
          bin.install "passbolt"
          bash_completion.install "completion/bash" => "passbolt"
          zsh_completion.install "completion/zsh" => "_passbolt"
          fish_completion.install "completion/fish" => "passbolt.fish"
          man1.install Dir["man/*"]
          # ...
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/passbolt/go-passbolt-cli/releases/download/v0.4.0-beta.1/go-passbolt-cli_0.4.0-beta.1_linux_arm64.tar.gz"
        sha256 "1ce7cadb72dfa1079fa82d897e916e0ba2e6c59ab0ec31ad28aaca35ff9b71bd"

        def install
          bin.install "passbolt"
          bash_completion.install "completion/bash" => "passbolt"
          zsh_completion.install "completion/zsh" => "_passbolt"
          fish_completion.install "completion/fish" => "passbolt.fish"
          man1.install Dir["man/*"]
          # ...
        end
      end
    end
  end
end
