# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoPassboltCli < Formula
  desc "A CLI tool to interact with Passbolt, a Open source Password Manager for Teams"
  homepage "https://github.com/passbolt/go-passbolt-cli"
  version "0.3.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/passbolt/go-passbolt-cli/releases/download/v0.3.1/go-passbolt-cli_0.3.1_darwin_amd64.tar.gz"
      sha256 "7fe47499566b92c85c16aac2f3c2586c1660af3a9dcbd83cfd75d7247a75b248"

      def install
        bin.install "passbolt"
        bash_completion.install "completion/bash" => "passbolt"
        zsh_completion.install "completion/zsh" => "_passbolt"
        fish_completion.install "completion/fish" => "passbolt.fish"
        man1.install Dir["man/*"]
        # ...
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/passbolt/go-passbolt-cli/releases/download/v0.3.1/go-passbolt-cli_0.3.1_darwin_arm64.tar.gz"
      sha256 "9981260bcc8d39e85257d8363c4b51414a798f7aafea88122462d90594b3750b"

      def install
        bin.install "passbolt"
        bash_completion.install "completion/bash" => "passbolt"
        zsh_completion.install "completion/zsh" => "_passbolt"
        fish_completion.install "completion/fish" => "passbolt.fish"
        man1.install Dir["man/*"]
        # ...
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/passbolt/go-passbolt-cli/releases/download/v0.3.1/go-passbolt-cli_0.3.1_linux_amd64.tar.gz"
      sha256 "4759c8a4fe2d8d3532af64266e832d87a81c3cb9ef6a36f1bfa5149e9cc6354d"

      def install
        bin.install "passbolt"
        bash_completion.install "completion/bash" => "passbolt"
        zsh_completion.install "completion/zsh" => "_passbolt"
        fish_completion.install "completion/fish" => "passbolt.fish"
        man1.install Dir["man/*"]
        # ...
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/passbolt/go-passbolt-cli/releases/download/v0.3.1/go-passbolt-cli_0.3.1_linux_arm64.tar.gz"
      sha256 "b8364c0a9724a701d942075d12eac9bda611a45c388ba0d69268eec5368b97da"

      def install
        bin.install "passbolt"
        bash_completion.install "completion/bash" => "passbolt"
        zsh_completion.install "completion/zsh" => "_passbolt"
        fish_completion.install "completion/fish" => "passbolt.fish"
        man1.install Dir["man/*"]
        # ...
      end
    end
  end
end
