# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoPassboltCli < Formula
  desc "A CLI tool to interact with Passbolt, a Open source Password Manager for Teams"
  homepage "https://github.com/passbolt/go-passbolt-cli"
  version "0.4.1"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/passbolt/go-passbolt-cli/releases/download/v0.4.1/go-passbolt-cli_0.4.1_darwin_amd64.tar.gz"
      sha256 "edda09e845db0e66bfc7b430772e6f34101355267f18ca0316f4c376d1a22518"

      def install
        bin.install "passbolt"
        bash_completion.install "completion/bash" => "passbolt"
        zsh_completion.install "completion/zsh" => "_passbolt"
        fish_completion.install "completion/fish" => "passbolt.fish"
        man1.install Dir["man/*"]
        # ...
      end
    end
    on_arm do
      url "https://github.com/passbolt/go-passbolt-cli/releases/download/v0.4.1/go-passbolt-cli_0.4.1_darwin_arm64.tar.gz"
      sha256 "e6b27324d4e7d123a9888e68ed96b8ee4d5155712bdf0433298d900d57f70c55"

      def install
        bin.install "passbolt"
        bash_completion.install "completion/bash" => "passbolt"
        zsh_completion.install "completion/zsh" => "_passbolt"
        fish_completion.install "completion/fish" => "passbolt.fish"
        man1.install Dir["man/*"]
        # ...
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/passbolt/go-passbolt-cli/releases/download/v0.4.1/go-passbolt-cli_0.4.1_linux_amd64.tar.gz"
        sha256 "38aca3864c63bf9ce57c372c0bf95dc8bed92d60b64cd47dd5fb65bcaa73b94f"

        def install
          bin.install "passbolt"
          bash_completion.install "completion/bash" => "passbolt"
          zsh_completion.install "completion/zsh" => "_passbolt"
          fish_completion.install "completion/fish" => "passbolt.fish"
          man1.install Dir["man/*"]
          # ...
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/passbolt/go-passbolt-cli/releases/download/v0.4.1/go-passbolt-cli_0.4.1_linux_arm64.tar.gz"
        sha256 "14772b2edeb2b738ce7a855acf2de1b48393bd0e3f6ecf8b80a2f7b2c4b76425"

        def install
          bin.install "passbolt"
          bash_completion.install "completion/bash" => "passbolt"
          zsh_completion.install "completion/zsh" => "_passbolt"
          fish_completion.install "completion/fish" => "passbolt.fish"
          man1.install Dir["man/*"]
          # ...
        end
      end
    end
  end
end
